stages:
  prepare_data:
    cmd: python train_model.py
    deps:
      - src/data_loader.py
      - src/model.py
      - src/train.py
      - src/evaluate.py
      - src/predict.py
      - train_model.py
      - params.yaml
    params:
      - data
      - model
      - training
      - finetune
      - output
      - prediction
    outs:
      - models/mobilenetv2_mask_detector.h5:
          cache: true
    metrics:
      - metrics.json:
          cache: false
    plots:
      - plots/training_history.json
      - plots/confusion_matrix.csv
